import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import authWalletRouter from "./auth-wallet";
import authEmailRouter from "./auth-email";
import authAgentRouter from "./auth-agent";
import authBotsRouter from "./auth-bots";
import authSpacechildRouter from "./auth-spacechild";
import identityRouter from "./identity";
import ledgerRouter from "./ledger";
import adminRouter from "./admin";
import artifactsRouter from "./artifacts";
import dropsRouter from "./drops";
import agentsRouter from "./agents";
import agentStorefrontRouter from "./agent-storefront";
import harvesterRouter from "./harvester";
import storefrontRouter from "./storefront";
import dashboardRouter from "./dashboard";
import shareRouter from "./share";
import webhooksRouter from "./webhooks";
import partnerEventsRouter from "./partner-events";
import nftRouter from "./nft";
import constellationRouter from "./constellation";
import connectorsRouter from "./connectors";
import marketplaceCombinedRouter from "./marketplace-combined";
import floorRouter from "./floor";
import predictionsRouter from "./predictions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(authWalletRouter);
router.use(authEmailRouter);
router.use(authAgentRouter);
router.use(authBotsRouter);
router.use(authSpacechildRouter);
router.use(identityRouter);
router.use(ledgerRouter);
router.use(adminRouter);
router.use(artifactsRouter);
router.use(dropsRouter);
router.use(agentsRouter);
router.use(agentStorefrontRouter);
router.use(harvesterRouter);
router.use(storefrontRouter);
router.use(dashboardRouter);
router.use(shareRouter);
router.use(webhooksRouter);
router.use(partnerEventsRouter);
router.use(nftRouter);
router.use(constellationRouter);
router.use(connectorsRouter);
router.use(marketplaceCombinedRouter);
router.use(floorRouter);
router.use(predictionsRouter);

export default router;
