// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/marketplace/Cyber.tsx": () => import("../components/mockups/marketplace/Cyber.tsx"),
  "./components/mockups/marketplace/Lantern.tsx": () => import("../components/mockups/marketplace/Lantern.tsx"),
  "./components/mockups/marketplace/Painterly.tsx": () => import("../components/mockups/marketplace/Painterly.tsx")
};
