// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chinatown/Cyber.tsx": () => import("../components/mockups/chinatown/Cyber.tsx"),
  "./components/mockups/chinatown/Lantern.tsx": () => import("../components/mockups/chinatown/Lantern.tsx"),
  "./components/mockups/chinatown/Painterly.tsx": () => import("../components/mockups/chinatown/Painterly.tsx")
};
