-- #255 (KAX-ADR-0002): record what has always been true.
--
-- Every KAX artifact is machine-generated by construction (harvested from
-- OpenBotCity bots) and nothing recorded it. connector_id is NOT a proxy:
-- it records provenance-of-ingest, not provenance-of-creation. Default TRUE
-- because every connector ingests agent-created work — the burden is on a
-- future non-AI path to prove otherwise, never the reverse.
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS machine_generated boolean NOT NULL DEFAULT true;
